version: "3"

services: 

    backend: 
        container_name: api
        build: ./api
        restart: always
        ports: 
            - "4000:4000"

    
    frontend:
        container_name: dashboard
        build: ./dashboard
        restart: always
        ports: 
            - "3000:3000"